apiVersion: v1
kind: Namespace
metadata:
  name: node-configuration-daemonset
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-patch-installer
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - node-patch-installer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-patch-installer
  namespace: node-configuration-daemonset
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-patch-installer
  namespace: node-configuration-daemonset
roleRef:
  kind: ClusterRole
  name: node-patch-installer
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: node-patch-installer
  namespace: node-configuration-daemonset
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: node-patch-installer
spec:
  privileged: true
  hostPID: true
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-patch-installer-script
  namespace: node-configuration-daemonset
data:
  install.sh: |
    #!/bin/bash

    exec /tmp/install/hot-patch/log4j-cve-2021-44228-hotpatch -w 1800 -m 10
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-patch-installer
  namespace: node-configuration-daemonset
spec:
  selector:
    matchLabels:
      job: node-patch-installer
  template:
    metadata:
      labels:
        job: node-patch-installer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
              - key: eks.amazonaws.com/compute-type
                operator: NotIn
                values:
                - fargate
      hostPID: true
      restartPolicy: Always
      initContainers:
      - image: quay.io/pengli1707/kubernetes-log4j-cve-2021-44228-node-agent:v0.0.5
        name: node-patch-installer
        securityContext:
          privileged: true
        volumeMounts:
        - name: install-script
          mountPath: /tmp
        - name: tmp-install
          mountPath: /host
        imagePullPolicy: Always 
      volumes:
      - name: install-script
        configMap:
          name: node-patch-installer-script
      - name: tmp-install
        hostPath:
          path: /tmp/install
      serviceAccountName: node-patch-installer
      tolerations:
      - operator: Exists
      containers:
      - image: "public.ecr.aws/eks-distro/kubernetes/pause:3.5"
        name: pause
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - all
